config/routes.rb
Rails.application.routes.draw do
  resources :followings, only: [:create, :destroy, :new]
  resources :opinions, except: %i[:destroy]
  resources :users, except: %i[:destroy, :edit]
  resources :user_sessions, only: [:new, :create, :destroy]
  root to: 'opinions#index'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/follow/:list', to: 'users#index'
  get '/talkey/:list', to: 'opinions#index'
  get '/startfollow/:id', to: 'followings#create'

end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :body, presence: true, length: { minimum: 3 }
  belongs_to :user

  scope :order_desc, -> { order(created_at: :desc) }

  has_many :followings, class_name: 'Following', foreign_key: 'user_id'
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  include OpinionsHelper
  before_action :authenticate_user!
  before_action :set_opinion, only: %i[show edit update destroy]

  def index
    set_lists
    @opinion = Opinion.new
    @whotofollow = User.with_attached_avatar.who_to_follow(current_user)
  end

  def show
    set_lists
  end

  def new
    @opinion = Opinion.new
    @opinions = current_user.opinions.order_desc
  end

  def edit; end

  def create
    @opinion = Opinion.new(opinion_params)
    @opinion.user_id = User.find_by(username: current_user.username.to_s).id
    respond_to do |format|
      if @opinion.save
        format.html { redirect_to new_opinion_path, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to new_opinion_path, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
  def display_opinions
    list_item = content_tag(:div, class: '') do
    end
    if @opinions.any?
      @opinions.order_desc.each do |opinion|
        list_item +=
          div(
            cloud(user_path(opinion.user), 'image m-4', opinion.user.avatar) +
            div(
              paragraph(opinion.user.fullname, 'user') +
              paragraph(opinion.body, 'opinion'),
              'd-flex flex-column justify-content-center'
            ), 'd-flex flex-row'
          )
      end
    end
    div(paragraph(@tag, 'head') + list_item, 'talk')
  end

  def set_lists
    case params[:list]
    when '1'
      @opinions = current_user.opinions.includes([:user])
      @ids = User.with_attached_avatar.fans(current_user).select(:id)
      @opinions = Opinion.all.order_desc.where(user_id: @ids).includes([:user])
      @tag = 'OPINIONS FROM FOLLOWERS'

    when '2'
      @ids = current_user.followings.select(:id).includes([:opinions])
      @opinions = Opinion.all.order_desc.where(user_id: @ids).includes([:user])
      @tag = 'OPINIONS FROM PEOPLE WHO YOU ARE FOLLOWING'

    else
      @opinions = Opinion.all.includes([:user])
      @tag = 'ALL OPINIONS FROM ALL USERS'
    end
  end

  private

  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  def opinion_params
    params.require(:opinion).permit(:body)
  end
end

app/views/opinions/_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions mt-3">
    <%= form.submit 'Update', class: 'btn-blue' %>
  </div>
<% end %>

app/views/opinions/_talk.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="talk ">
    <div class="d-flex bd-highlight align-items-center p-4">
      <div class="bd-highlight w-100">
        <%= form.label :body %>
        <%= form.text_area :body, class: " bd-highlight" %>
      </div>

      <div class="actions flex-shrink">
        <%= form.submit 'Talkey', class: "btn-blue w-100" %>
      </div>
    </div>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h1 class="m-auto">Editing Opinion</h1>
  </div>
  <div class="row">
    <div class="m-auto">
      <%= render 'form', opinion: @opinion%>
    </div>
  </div>

  <div class="row">
    <div class="m-auto">
    </div>
  </div>
</div>

app/views/opinions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!--PEOPLE-->
    <div class="col-lg-9 col-md-12 col-sm-12">
      <!--MENU GOTO WHITE-->
      <div class="row">
        <div class="portada ">
          <%= image('', 'cover w-100 h-100', current_user.cover_image ) %>
        </div>
      </div>
      
      <div class="row m-auto">
        <%= display_goto_menu %>
      </div>
      
      <!--TWEETS-->
      <div class="row mt-2">
        <% if current_user? %>
          <div class="col-12">
            <%= render 'talk', opinion: @opinion %>
          </div>
        <% end %>
      </div>

      <div class="row mt-2">
        <div class= "col-12">
            <%= display_opinions %>  
        </div>
      </div>
    </div>
    <!--FOLLOWED BY-->
    <div class="col-lg-3 col-md-12 col-sm-12 p-2">
      <!--WHO TO FOLLOW TAG-->
      <div class="row pt-4">
        <p class="m-auto">WHO TO FOLLOW</p>
      </div>
      <!--FOLLOWEB PROFILE-->
      <%= whotofollow %>
    </div>
  </div>
</div>

    <%#= link_to 'Show', opinion %>
    <%#= link_to 'Edit', edit_opinion_path(opinion) %>
    <%#= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/opinions/new.html.erb
<!--MENU GOTO WHITE-->
<div class="container-fluid">
<div class="row">
  <%= display_goto_menu %>
</div>
<div class="row">
  <div class="col-12">
    <h3 class="d-flex justify-content-center">Create a new opinion and let's talk!</h3>
  </div>
  <div class="col-12">
    <%= render 'talk', opinion: @opinion %>
  </div>
    <div class="col-12">
    <h3 class="d-flex justify-content-center">Your talkeys</h3>
  </div>
  <div class= "col-12">
  <div class="talk">
    <% @opinions.each do |opinion| %>
      <div class="d-flex flex-row">
      <div>
        <%= link_to edit_opinion_path(opinion), class: 'level-item mr-2' do %>
            <i class="fa fa-sm fa-pencil fill-blue"></i>
        <% end %>
      </div>
        <div class="d-flex flex-column justify-content-center">
          <p class="opinion"><%= opinion.body %></p>
        </div>
        
      </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/opinions/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @opinion.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @opinion.user_id %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>