config/routes.rb
Rails.application.routes.draw do
  resources :followings, only: [:create, :destroy, :new]
  resources :opinions, except: %i[:destroy]
  resources :users, except: %i[:destroy, :edit]
  resources :user_sessions, only: [:new, :create, :destroy]
  root to: 'opinions#index'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  get '/follow/:list', to: 'users#index'
  get '/talkey/:list', to: 'opinions#index'
  get '/startfollow/:id', to: 'followings#create'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  include FollowingsHelper
  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user.nil?
      flash.now.alert = 'Login failed'
      render action: :new
    else
      session[:name] = user.fullname
      session[:username] = user.username
      redirect_to(:users, notice: 'Sign In Succesful.')
    end
  end

  def destroy
    logout
    redirect_to(:users, alert: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def logout
    session.destroy
  end

  def current_user
    @current_user = (User.find_by(username: session[:username]) if session[:name])
  end

  def current_user?
    @current_user = User.find_by(username: session[:username])
    if @current_user.nil?
      false
    else
      true
    end
  end

  def authenticate_user!
    redirect_to login_path unless current_user?
    flash.now.alert = 'Login failed.' unless current_user?
  end
end

app/views/user_sessions/_partial.html.erb
<%= form_with method: 'post', url: user_sessions_path, local: true do |form| %>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div class="btn-blue">
    <%= form.submit 'Sign in', class: 'btn-blue' %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
  <div class="center pb-5 m-auto">
    <%= link_to image_tag('talky.png', alt: 'Logo', class: 'w-50 m-4 p-4'), users_path %>
    <h1 class="font-lg">Log in to Talkey</h1>
    <%= render 'partial'%>
    <%= link_to 'Create a new account', new_user_path %>
  </div>